# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# 每日早8点到晚8点每6小时运行一次

name: 中青自动阅读

on:
  workflow_dispatch:
  schedule:
     - cron: '30 0,4 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ: ${{ secrets.YOUTH_READ11 }}
      YOUTH_READ2: ${{ secrets.YOUTH_READ12 }}
      YOUTH_READ3: ${{ secrets.YOUTH_READ13 }}
      YOUTH_READ4: ${{ secrets.YOUTH_READ14 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ15 }}
      YOUTH_READ6: ${{ secrets.YOUTH_READ16 }}
      TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点自动阅读一】'
        if: env.YOUTH_READ
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ11 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME11 }}

      - name: '运行 【中青看点自动阅读二】'
        if: env.YOUTH_READ2
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ12 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME12 }}
          
      - name: '运行 【中青看点自动阅读三】'
        if: env.YOUTH_READ3
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ13 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME13 }}
          
      - name: '运行 【中青看点自动阅读四】'
        if: env.YOUTH_READ4
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ14 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME14 }}

      - name: '运行 【中青看点自动阅读五】'
        if: env.YOUTH_READ5
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ15 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME15 }}
          
      - name: '运行 【中青看点自动阅读六】'
        if: env.YOUTH_READ6
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ16 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME16 }}
